name: kbin_api
description: The easiest and powerful Dart/Flutter library for Kbin API.
version: 0.0.1
repository: https://github.com/getBoolean/kbin_api
issue_tracker: https://github.com/getBoolean/kbin_api/issues

environment:
  sdk: ">=3.0.0 <=4.0.0"

dependencies:
  http: ^0.13.5
  universal_io: ^2.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  dart_mappable: ^3.1.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  import_sorter: ^4.6.0
  mockito: ^5.4.0
  dart_mappable_builder: ^3.1.1

import_sorter:
  emojis: true
